spring.application.name=demo


# These configuration is done for connecting Spring Boot to Postgresql. Data's are not will be coming from postgresql.
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
spring.datasource.username=postgres
spring.datasource.password=apurv998
spring.datasource.driver-class-name=org.postgresql.Driver

# Neeche die gye line se Table bnti hai
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# for PostgreSQL, working with large object, important property as listed below
spring.datasource.hikari.auto-commit=false
